set_property PACKAGE_PIN V17 [get_ports {chiplink_tx_data[0]}]
set_property PACKAGE_PIN V18 [get_ports {chiplink_tx_data[1]}]
set_property PACKAGE_PIN K19 [get_ports {chiplink_tx_data[2]}]
set_property PACKAGE_PIN J19 [get_ports {chiplink_tx_data[3]}]
set_property PACKAGE_PIN J18 [get_ports {chiplink_tx_data[4]}]
set_property PACKAGE_PIN H18 [get_ports {chiplink_tx_data[5]}]
set_property PACKAGE_PIN M14 [get_ports {chiplink_tx_data[6]}]
set_property PACKAGE_PIN M15 [get_ports {chiplink_tx_data[7]}]
set_property PACKAGE_PIN L15 [get_ports {chiplink_tx_data[8]}]
set_property PACKAGE_PIN L14 [get_ports {chiplink_tx_data[9]}]
set_property PACKAGE_PIN J14 [get_ports {chiplink_tx_data[10]}]
set_property PACKAGE_PIN K14 [get_ports {chiplink_tx_data[11]}]
set_property PACKAGE_PIN F16 [get_ports {chiplink_tx_data[12]}]
set_property PACKAGE_PIN F17 [get_ports {chiplink_tx_data[13]}]
set_property PACKAGE_PIN D18 [get_ports {chiplink_tx_data[14]}]
set_property PACKAGE_PIN E17 [get_ports {chiplink_tx_data[15]}]
set_property PACKAGE_PIN E19 [get_ports {chiplink_tx_data[16]}]
set_property PACKAGE_PIN E18 [get_ports {chiplink_tx_data[17]}]
set_property PACKAGE_PIN H15 [get_ports {chiplink_tx_data[18]}]
set_property PACKAGE_PIN G15 [get_ports {chiplink_tx_data[19]}]
set_property PACKAGE_PIN H20 [get_ports {chiplink_tx_data[20]}]
set_property PACKAGE_PIN J20 [get_ports {chiplink_tx_data[21]}]
set_property PACKAGE_PIN L20 [get_ports {chiplink_tx_data[22]}]
set_property PACKAGE_PIN L19 [get_ports {chiplink_tx_data[23]}]
set_property PACKAGE_PIN M20 [get_ports {chiplink_tx_data[24]}]
set_property PACKAGE_PIN M19 [get_ports {chiplink_tx_data[25]}]
set_property PACKAGE_PIN N20 [get_ports {chiplink_tx_data[26]}]
set_property PACKAGE_PIN P20 [get_ports {chiplink_tx_data[27]}]
set_property PACKAGE_PIN T20 [get_ports {chiplink_tx_data[28]}]
set_property PACKAGE_PIN U20 [get_ports {chiplink_tx_data[29]}]
set_property PACKAGE_PIN V20 [get_ports {chiplink_tx_data[30]}]
set_property PACKAGE_PIN W20 [get_ports {chiplink_tx_data[31]}]
set_property PACKAGE_PIN V16 [get_ports chiplink_tx_rst]
set_property PACKAGE_PIN K18 [get_ports chiplink_tx_clk]
set_property PACKAGE_PIN W16 [get_ports chiplink_tx_send]

set_property PACKAGE_PIN T16 [get_ports {chiplink_rx_data[0]}]
set_property PACKAGE_PIN U17 [get_ports {chiplink_rx_data[1]}]
set_property PACKAGE_PIN W18 [get_ports {chiplink_rx_data[2]}]
set_property PACKAGE_PIN W19 [get_ports {chiplink_rx_data[3]}]
set_property PACKAGE_PIN U19 [get_ports {chiplink_rx_data[4]}]
set_property PACKAGE_PIN T19 [get_ports {chiplink_rx_data[5]}]
set_property PACKAGE_PIN R19 [get_ports {chiplink_rx_data[6]}]
set_property PACKAGE_PIN Y18 [get_ports {chiplink_rx_data[7]}]
set_property PACKAGE_PIN U13 [get_ports {chiplink_rx_data[8]}]
set_property PACKAGE_PIN T15 [get_ports {chiplink_rx_data[9]}]
set_property PACKAGE_PIN T14 [get_ports {chiplink_rx_data[10]}]
set_property PACKAGE_PIN P16 [get_ports {chiplink_rx_data[11]}]
set_property PACKAGE_PIN P15 [get_ports {chiplink_rx_data[12]}]
set_property PACKAGE_PIN R18 [get_ports {chiplink_rx_data[13]}]
set_property PACKAGE_PIN T17 [get_ports {chiplink_rx_data[14]}]
set_property PACKAGE_PIN P19 [get_ports {chiplink_rx_data[15]}]
set_property PACKAGE_PIN R17 [get_ports {chiplink_rx_data[16]}]
set_property PACKAGE_PIN R16 [get_ports {chiplink_rx_data[17]}]
set_property PACKAGE_PIN N16 [get_ports {chiplink_rx_data[18]}]
set_property PACKAGE_PIN N15 [get_ports {chiplink_rx_data[19]}]
set_property PACKAGE_PIN W13 [get_ports {chiplink_rx_data[20]}]
set_property PACKAGE_PIN V12 [get_ports {chiplink_rx_data[21]}]
set_property PACKAGE_PIN T11 [get_ports {chiplink_rx_data[22]}]
set_property PACKAGE_PIN T10 [get_ports {chiplink_rx_data[23]}]
set_property PACKAGE_PIN N18 [get_ports {chiplink_rx_data[24]}]
set_property PACKAGE_PIN L16 [get_ports {chiplink_rx_data[25]}]
set_property PACKAGE_PIN L17 [get_ports {chiplink_rx_data[26]}]
set_property PACKAGE_PIN V15 [get_ports {chiplink_rx_data[27]}]
set_property PACKAGE_PIN W15 [get_ports {chiplink_rx_data[28]}]
set_property PACKAGE_PIN K16 [get_ports {chiplink_rx_data[29]}]
set_property PACKAGE_PIN J16 [get_ports {chiplink_rx_data[30]}]
set_property PACKAGE_PIN K17 [get_ports {chiplink_rx_data[31]}]
set_property PACKAGE_PIN U14 [get_ports chiplink_rx_rst]
set_property PACKAGE_PIN N17 [get_ports chiplink_rx_clk]
set_property PACKAGE_PIN U15 [get_ports chiplink_rx_send]
set_property PACKAGE_PIN Y19 [get_ports chiplink_cpu_int]

set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_tx_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_tx_rst]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_tx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_tx_send]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[26]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[27]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[28]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[29]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[30]}]
set_property IOSTANDARD LVCMOS33 [get_ports {chiplink_rx_data[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_rx_rst]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_rx_clk]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_rx_send]
set_property IOSTANDARD LVCMOS33 [get_ports chiplink_cpu_int]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {chiplink_tx_clk_IBUF}]
# create_clock -period 40.000 -name chiplink_tx_clk -waveform {0.000 20.000} [get_ports {chiplink_tx_clk}]
# create_generated_clock -name chiplink_tx_clk -edges {1 2 3} -source [get_pins {design_1_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] [get_ports chiplink_tx_clk]
create_generated_clock -name chiplink_tx_clk -source [get_pins design_1_i/chiplink_ctrl_0/clk] -divide_by 1 [get_ports chiplink_tx_clk]
# create_generated_clock -name chiplink_tx_clk -edges {1 2 3} -source [get_clocks clk_fpga_0] [get_ports chiplink_tx_clk]
set_input_delay -clock [get_clocks chiplink_tx_clk] -min -add_delay 0.680 [get_ports {chiplink_tx_data[*]}]
set_input_delay -clock [get_clocks chiplink_tx_clk] -max -add_delay 2.500 [get_ports {chiplink_tx_data[*]}]
set_input_delay -clock [get_clocks chiplink_tx_clk] -min -add_delay 0.680 [get_ports chiplink_tx_rst]
set_input_delay -clock [get_clocks chiplink_tx_clk] -max -add_delay 2.500 [get_ports chiplink_tx_rst]
set_input_delay -clock [get_clocks chiplink_tx_clk] -min -add_delay 0.680 [get_ports chiplink_tx_send]
set_input_delay -clock [get_clocks chiplink_tx_clk] -max -add_delay 2.500 [get_ports chiplink_tx_send]

create_clock -period 40.000 -name chiplink_rx_clk -waveform {0.000 20.000}
set_output_delay -clock [get_clocks chiplink_rx_clk] -min -add_delay 0.680 [get_ports {chiplink_rx_data[*]}]
set_output_delay -clock [get_clocks chiplink_rx_clk] -max -add_delay 2.500 [get_ports {chiplink_rx_data[*]}]
set_output_delay -clock [get_clocks chiplink_rx_clk] -min -add_delay 0.680 [get_ports chiplink_rx_rst]
set_output_delay -clock [get_clocks chiplink_rx_clk] -max -add_delay 2.500 [get_ports chiplink_rx_rst]
set_output_delay -clock [get_clocks chiplink_rx_clk] -min -add_delay 0.680 [get_ports chiplink_rx_send]
set_output_delay -clock [get_clocks chiplink_rx_clk] -max -add_delay 2.500 [get_ports chiplink_rx_send]




